theme: jekyll-theme-cayman
title: è®¡æ´‹çš„åšå®¢ğŸ’ª
description: æ²¡æœ‰çƒ­å¿±ï¼Œä¸–é—´ä¾¿æ— è¿›æ­¥
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]